### ISSUE TITLE
Project 3.14

### ISSUE THREAD

**Issue by anpolychrono** [angelou/dev-friendly-cafes-patras#3]
This place here : https://goo.gl/maps/4KAQpK3d1VhUfhtK6 has good coffee , a unique ΚΥΚΑΩ beer which can be found only here and a very good Internet Speed (will post the values next time). It is not for a full day of work but you can spent a couple of hours there for sure. During the morning  and noon is less busy. They do not server lunch or brunch but you have many options in walking distance.

**Comment by angelou** [comment]
Thanks @anpolychrono ! I always wanted to try that place.

**Comment by angelou** [comment]
Merged the description.
